In [1]:
import pandas as pd

In [7]:
df=pd.read_csv(r"C:\Users\vaibh\Downloads\archive\final_job_list.csv")
df

,Title,Company,Location,Type of Positions,Job Description,Salary,Identified_Skills
0,"Staff Applied Scientist, Marketplace",ThredUp Inc.,CA,Full-time,\nAbout thredUP thredUP is transforming resale...,190000.0,"['python', 'machine learning', 'aws', 'sql']"
1,Prompt Engineer for Generative AI (chatbot and...,Vicarious Talent Agency,WA,Full-time,"We are Vicarious, a talent agency that represe...",70000.0,"['python', 'machine learning', 'deep learning'..."
2,Data Systems Analyst/Architect,General Dynamics Information Technology,Remote,Full-time,Clearance Level None Category Data Science Loc...,104000.0,"['machine learning', 'aws', 'azure', 'nosql', ..."
3,AIOps Principle Data Scientist,CVS Health,CT,Full-time,\nBring your heart to CVS Health. Every one of...,140000.0,"['python', 'machine learning', 'aws', 'gcp']"
4,Sr. Data Scientist,Altak Group,Remote,Full-time,Job Summary:\nWe are seeking an experienced Da...,136000.0,"['python', 'machine learning', 'tableau', 'aws..."
...,...,...,...,...,...,...,...
687,Senior Staff AI Data Engineer,Recruiting From Scratch,TX,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
688,Senior Staff AI Data Engineer,Recruiting From Scratch,CO,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
689,Senior Staff AI Data Engineer,Recruiting From Scratch,HI,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
690,Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
691,Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."

In [9]:
a= pd.read_csv(r"final_job_list.csv")
a

,Title,Company,Location,Type of Positions,Job Description,Salary,Identified_Skills
0,"Staff Applied Scientist, Marketplace",ThredUp Inc.,CA,Full-time,\nAbout thredUP thredUP is transforming resale...,190000.0,"['python', 'machine learning', 'aws', 'sql']"
1,Prompt Engineer for Generative AI (chatbot and...,Vicarious Talent Agency,WA,Full-time,"We are Vicarious, a talent agency that represe...",70000.0,"['python', 'machine learning', 'deep learning'..."
2,Data Systems Analyst/Architect,General Dynamics Information Technology,Remote,Full-time,Clearance Level None Category Data Science Loc...,104000.0,"['machine learning', 'aws', 'azure', 'nosql', ..."
3,AIOps Principle Data Scientist,CVS Health,CT,Full-time,\nBring your heart to CVS Health. Every one of...,140000.0,"['python', 'machine learning', 'aws', 'gcp']"
4,Sr. Data Scientist,Altak Group,Remote,Full-time,Job Summary:\nWe are seeking an experienced Da...,136000.0,"['python', 'machine learning', 'tableau', 'aws..."
...,...,...,...,...,...,...,...
687,Senior Staff AI Data Engineer,Recruiting From Scratch,TX,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
688,Senior Staff AI Data Engineer,Recruiting From Scratch,CO,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
689,Senior Staff AI Data Engineer,Recruiting From Scratch,HI,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
690,Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
691,Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."

# open csv file from URL

In [19]:


import requests
from io import StringIO

url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

headers={"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url, headers=headers)

data=StringIO(req.text)

a=pd.read_csv(data)

In [14]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

# Fixed: Added '=' and '{}' to correctly define the dictionary
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url, headers=headers)

# Fixed: Added '=' to assign the StringIO object to data
data = StringIO(req.text)

df = pd.read_csv(data)

In [15]:
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [20]:
a

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

# set parameter

In [24]:
pd.read_csv(r"students.csv.csv",sep=',',names=["names","ages","ids","feess","colleges"])

     names ages  ids   feess    colleges
0     name  age   id    fees     college
1    Aarav   24  101   65000        YCCE
2     Riya   21  102     NaN        VNIT
3    Kabir   22  103   40000  GH Raisoni
4    Sneha  NaN  104   95000        yccc
5    mohit   20  105   95000  GH Raisoni
6    Priya   25  106  120000       RCOEM
7    Arjun   22  NaN     NaN       RCOEM
8     Neha   22  108  115000  GH Raisoni
9   Vikram   24  109  110000     SB Jain
10  Anjali   19  NaN  110000       RCOEM
11   Karan   20  NaN     NaN       RCOEM
12   Pooja   24  NaN   50000  GH Raisoni
13    Amit  NaN  NaN   60000       RCOEM
14   Divya   20  NaN   70000         ycc
15   Rahul   25  NaN   80000  GH Raisoni
16    Isha   22  NaN     NaN  GH Raisoni
17  Manish  NaN  117   55000        VNIT
18  Sakshi   25  118  105000     SB Jain
19    ranu  NaN  NaN     NaN         ycc
20   Tanvi   20  120   45000       RCOEM
21  Nikhil   23  121  110000     SB Jain
22   Megha   22  122     NaN       RCOEM
23   Harsh   19  123   95000        VNIT
24   Kavya   25  124   75000  GH Raisoni
25  Sameer   21  125  110000         ycc

# index call parameter

In [26]:
pd.read_csv("final_job_list.csv",index_col="Title")

,Company,Location,Type of Positions,Job Description,Salary,Identified_Skills
Title,,,,,,
"Staff Applied Scientist, Marketplace",ThredUp Inc.,CA,Full-time,\nAbout thredUP thredUP is transforming resale...,190000.0,"['python', 'machine learning', 'aws', 'sql']"
Prompt Engineer for Generative AI (chatbot and image),Vicarious Talent Agency,WA,Full-time,"We are Vicarious, a talent agency that represe...",70000.0,"['python', 'machine learning', 'deep learning'..."
Data Systems Analyst/Architect,General Dynamics Information Technology,Remote,Full-time,Clearance Level None Category Data Science Loc...,104000.0,"['machine learning', 'aws', 'azure', 'nosql', ..."
AIOps Principle Data Scientist,CVS Health,CT,Full-time,\nBring your heart to CVS Health. Every one of...,140000.0,"['python', 'machine learning', 'aws', 'gcp']"
Sr. Data Scientist,Altak Group,Remote,Full-time,Job Summary:\nWe are seeking an experienced Da...,136000.0,"['python', 'machine learning', 'tableau', 'aws..."
...,...,...,...,...,...,...
Senior Staff AI Data Engineer,Recruiting From Scratch,TX,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
Senior Staff AI Data Engineer,Recruiting From Scratch,CO,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
Senior Staff AI Data Engineer,Recruiting From Scratch,HI,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."
Senior Staff AI Data Engineer,Recruiting From Scratch,CA,Full-time,\n\n\nWho is \nRecruiting from Scratch \n: \n\...,160000.0,"['python', 'pandas', 'machine learning', 'aws'..."

# Header Parameter

In [27]:
pd.read_csv("students.csv.csv",header=1)

     Aarav    24    101     65000        YCCE
0     Riya  21.0  102.0       NaN        VNIT
1    Kabir  22.0  103.0   40000.0  GH Raisoni
2    Sneha   NaN  104.0   95000.0        yccc
3    mohit  20.0  105.0   95000.0  GH Raisoni
4    Priya  25.0  106.0  120000.0       RCOEM
5    Arjun  22.0    NaN       NaN       RCOEM
6     Neha  22.0  108.0  115000.0  GH Raisoni
7   Vikram  24.0  109.0  110000.0     SB Jain
8   Anjali  19.0    NaN  110000.0       RCOEM
9    Karan  20.0    NaN       NaN       RCOEM
10   Pooja  24.0    NaN   50000.0  GH Raisoni
11    Amit   NaN    NaN   60000.0       RCOEM
12   Divya  20.0    NaN   70000.0         ycc
13   Rahul  25.0    NaN   80000.0  GH Raisoni
14    Isha  22.0    NaN       NaN  GH Raisoni
15  Manish   NaN  117.0   55000.0        VNIT
16  Sakshi  25.0  118.0  105000.0     SB Jain
17    ranu   NaN    NaN       NaN         ycc
18   Tanvi  20.0  120.0   45000.0       RCOEM
19  Nikhil  23.0  121.0  110000.0     SB Jain
20   Megha  22.0  122.0       NaN       RCOEM
21   Harsh  19.0  123.0   95000.0        VNIT
22   Kavya  25.0  124.0   75000.0  GH Raisoni
23  Sameer  21.0  125.0  110000.0         ycc

# use_col parameter

In [29]:
pd.read_csv("students.csv.csv",usecols=["name",	"age"])

      name   age
0    Aarav  24.0
1     Riya  21.0
2    Kabir  22.0
3    Sneha   NaN
4    mohit  20.0
5    Priya  25.0
6    Arjun  22.0
7     Neha  22.0
8   Vikram  24.0
9   Anjali  19.0
10   Karan  20.0
11   Pooja  24.0
12    Amit   NaN
13   Divya  20.0
14   Rahul  25.0
15    Isha  22.0
16  Manish   NaN
17  Sakshi  25.0
18    ranu   NaN
19   Tanvi  20.0
20  Nikhil  23.0
21   Megha  22.0
22   Harsh  19.0
23   Kavya  25.0
24  Sameer  21.0

# Squeeze parameter

In [31]:
pd.read_csv("students.csv.csv",usecols=["name"])

      name
0    Aarav
1     Riya
2    Kabir
3    Sneha
4    mohit
5    Priya
6    Arjun
7     Neha
8   Vikram
9   Anjali
10   Karan
11   Pooja
12    Amit
13   Divya
14   Rahul
15    Isha
16  Manish
17  Sakshi
18    ranu
19   Tanvi
20  Nikhil
21   Megha
22   Harsh
23   Kavya
24  Sameer

# Skip rows nrosw parameter

In [36]:
pd.read_csv("students.csv.csv",skiprows=[0,5])

     Aarav    24    101     65000        YCCE
0     Riya  21.0  102.0       NaN        VNIT
1    Kabir  22.0  103.0   40000.0  GH Raisoni
2    Sneha   NaN  104.0   95000.0        yccc
3    Priya  25.0  106.0  120000.0       RCOEM
4    Arjun  22.0    NaN       NaN       RCOEM
5     Neha  22.0  108.0  115000.0  GH Raisoni
6   Vikram  24.0  109.0  110000.0     SB Jain
7   Anjali  19.0    NaN  110000.0       RCOEM
8    Karan  20.0    NaN       NaN       RCOEM
9    Pooja  24.0    NaN   50000.0  GH Raisoni
10    Amit   NaN    NaN   60000.0       RCOEM
11   Divya  20.0    NaN   70000.0         ycc
12   Rahul  25.0    NaN   80000.0  GH Raisoni
13    Isha  22.0    NaN       NaN  GH Raisoni
14  Manish   NaN  117.0   55000.0        VNIT
15  Sakshi  25.0  118.0  105000.0     SB Jain
16    ranu   NaN    NaN       NaN         ycc
17   Tanvi  20.0  120.0   45000.0       RCOEM
18  Nikhil  23.0  121.0  110000.0     SB Jain
19   Megha  22.0  122.0       NaN       RCOEM
20   Harsh  19.0  123.0   95000.0        VNIT
21   Kavya  25.0  124.0   75000.0  GH Raisoni
22  Sameer  21.0  125.0  110000.0         ycc

In [37]:
pd.read_csv("students.csv.csv",nrows=100)

      name   age     id      fees     college
0    Aarav  24.0  101.0   65000.0        YCCE
1     Riya  21.0  102.0       NaN        VNIT
2    Kabir  22.0  103.0   40000.0  GH Raisoni
3    Sneha   NaN  104.0   95000.0        yccc
4    mohit  20.0  105.0   95000.0  GH Raisoni
5    Priya  25.0  106.0  120000.0       RCOEM
6    Arjun  22.0    NaN       NaN       RCOEM
7     Neha  22.0  108.0  115000.0  GH Raisoni
8   Vikram  24.0  109.0  110000.0     SB Jain
9   Anjali  19.0    NaN  110000.0       RCOEM
10   Karan  20.0    NaN       NaN       RCOEM
11   Pooja  24.0    NaN   50000.0  GH Raisoni
12    Amit   NaN    NaN   60000.0       RCOEM
13   Divya  20.0    NaN   70000.0         ycc
14   Rahul  25.0    NaN   80000.0  GH Raisoni
15    Isha  22.0    NaN       NaN  GH Raisoni
16  Manish   NaN  117.0   55000.0        VNIT
17  Sakshi  25.0  118.0  105000.0     SB Jain
18    ranu   NaN    NaN       NaN         ycc
19   Tanvi  20.0  120.0   45000.0       RCOEM
20  Nikhil  23.0  121.0  110000.0     SB Jain
21   Megha  22.0  122.0       NaN       RCOEM
22   Harsh  19.0  123.0   95000.0        VNIT
23   Kavya  25.0  124.0   75000.0  GH Raisoni
24  Sameer  21.0  125.0  110000.0         ycc

# Encoding Parameter

In [38]:
pd.read_csv("students.csv.csv",encoding='latin-1')

      name   age     id      fees     college
0    Aarav  24.0  101.0   65000.0        YCCE
1     Riya  21.0  102.0       NaN        VNIT
2    Kabir  22.0  103.0   40000.0  GH Raisoni
3    Sneha   NaN  104.0   95000.0        yccc
4    mohit  20.0  105.0   95000.0  GH Raisoni
5    Priya  25.0  106.0  120000.0       RCOEM
6    Arjun  22.0    NaN       NaN       RCOEM
7     Neha  22.0  108.0  115000.0  GH Raisoni
8   Vikram  24.0  109.0  110000.0     SB Jain
9   Anjali  19.0    NaN  110000.0       RCOEM
10   Karan  20.0    NaN       NaN       RCOEM
11   Pooja  24.0    NaN   50000.0  GH Raisoni
12    Amit   NaN    NaN   60000.0       RCOEM
13   Divya  20.0    NaN   70000.0         ycc
14   Rahul  25.0    NaN   80000.0  GH Raisoni
15    Isha  22.0    NaN       NaN  GH Raisoni
16  Manish   NaN  117.0   55000.0        VNIT
17  Sakshi  25.0  118.0  105000.0     SB Jain
18    ranu   NaN    NaN       NaN         ycc
19   Tanvi  20.0  120.0   45000.0       RCOEM
20  Nikhil  23.0  121.0  110000.0     SB Jain
21   Megha  22.0  122.0       NaN       RCOEM
22   Harsh  19.0  123.0   95000.0        VNIT
23   Kavya  25.0  124.0   75000.0  GH Raisoni
24  Sameer  21.0  125.0  110000.0         ycc

# Skip bad Line

In [43]:
pd.read_csv("students.csv.csv",sep=",", encoding='latin-1',on_bad_lines=skip)

NameError: name 'skip' is not defined

# dtypes Parameter

In [45]:
pd.read_csv("students.csv.csv",dtype={"id":int})

ValueError: Integer column has NA values in column 2

# Handling Dates

In [47]:
pd.read_csv("students.csv.csv",parse_dates = ['date']).info()

ValueError: Missing column provided to 'parse_dates': 'date'

# Covertors

In [49]:
def rename(name):
    if name == "GH Raisoni":
        return "GHR"
    else:
        return name
rename("GH Raisoni")

'GHR'

In [53]:
pd.read_csv("students.csv.csv",converters={"college":rename})

      name   age     id      fees  college
0    Aarav  24.0  101.0   65000.0     YCCE
1     Riya  21.0  102.0       NaN     VNIT
2    Kabir  22.0  103.0   40000.0      GHR
3    Sneha   NaN  104.0   95000.0     yccc
4    mohit  20.0  105.0   95000.0      GHR
5    Priya  25.0  106.0  120000.0    RCOEM
6    Arjun  22.0    NaN       NaN    RCOEM
7     Neha  22.0  108.0  115000.0      GHR
8   Vikram  24.0  109.0  110000.0  SB Jain
9   Anjali  19.0    NaN  110000.0    RCOEM
10   Karan  20.0    NaN       NaN    RCOEM
11   Pooja  24.0    NaN   50000.0      GHR
12    Amit   NaN    NaN   60000.0    RCOEM
13   Divya  20.0    NaN   70000.0      ycc
14   Rahul  25.0    NaN   80000.0      GHR
15    Isha  22.0    NaN       NaN      GHR
16  Manish   NaN  117.0   55000.0     VNIT
17  Sakshi  25.0  118.0  105000.0  SB Jain
18    ranu   NaN    NaN       NaN      ycc
19   Tanvi  20.0  120.0   45000.0    RCOEM
20  Nikhil  23.0  121.0  110000.0  SB Jain
21   Megha  22.0  122.0       NaN    RCOEM
22   Harsh  19.0  123.0   95000.0     VNIT
23   Kavya  25.0  124.0   75000.0      GHR
24  Sameer  21.0  125.0  110000.0      ycc

# na_values parameter

In [55]:
pd.read_csv("students.csv.csv",na_values= ["GH Raisoni"])

      name   age     id      fees  college
0    Aarav  24.0  101.0   65000.0     YCCE
1     Riya  21.0  102.0       NaN     VNIT
2    Kabir  22.0  103.0   40000.0      NaN
3    Sneha   NaN  104.0   95000.0     yccc
4    mohit  20.0  105.0   95000.0      NaN
5    Priya  25.0  106.0  120000.0    RCOEM
6    Arjun  22.0    NaN       NaN    RCOEM
7     Neha  22.0  108.0  115000.0      NaN
8   Vikram  24.0  109.0  110000.0  SB Jain
9   Anjali  19.0    NaN  110000.0    RCOEM
10   Karan  20.0    NaN       NaN    RCOEM
11   Pooja  24.0    NaN   50000.0      NaN
12    Amit   NaN    NaN   60000.0    RCOEM
13   Divya  20.0    NaN   70000.0      ycc
14   Rahul  25.0    NaN   80000.0      NaN
15    Isha  22.0    NaN       NaN      NaN
16  Manish   NaN  117.0   55000.0     VNIT
17  Sakshi  25.0  118.0  105000.0  SB Jain
18    ranu   NaN    NaN       NaN      ycc
19   Tanvi  20.0  120.0   45000.0    RCOEM
20  Nikhil  23.0  121.0  110000.0  SB Jain
21   Megha  22.0  122.0       NaN    RCOEM
22   Harsh  19.0  123.0   95000.0     VNIT
23   Kavya  25.0  124.0   75000.0      NaN
24  Sameer  21.0  125.0  110000.0      ycc

# Loading a huge dataset  in chunks

In [72]:
dfs=pd.read_csv("students.csv.csv",chunksize=5)

In [73]:
for chunk in dfs:
    print(chunk.shape)

(5, 5)
(5, 5)
(5, 5)
(5, 5)
(5, 5)