# Pandas Propiler

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tested.csv')

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
!pip install sweetviz

Requirement already satisfied: sweetviz in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (3.0.6)
Requirement already satisfied: numpy>=1.16.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (2.5.3)
Requirement already satisfied: matplotlib>=3.1.3 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (3.11.2)
Requirement already satisfied: tqdm>=4.43.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (4.70.1)
Requirement already satisfied: scipy>=1.3.2 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (1.18.1)
Requirement already satisfied: jinja2>=2.11.1 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.4)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in C:\Users\vaibh\AppData\Roaming\Python\Python314\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)

In [6]:
pip install pandas-profiling

Collecting pandas-profiling
  Using cached pandas_profiling-3.2.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Using cached joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (1.18.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (3.0.6)
Requirement already satisfied: matplotlib>=3.2.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (3.11.2)
Collecting pydantic>=1.8.1 (from pandas-profiling)
  Using cached pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
Requirement already satisfied: PyYAML>=5.0.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (6.0.3)
Requirement already satisfied: jinja2>=2.11.1 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (3.1.6)
Collecting markupsafe~=2.1.1 (from pandas-profiling)
  Using cached MarkupSafe-2.1.5.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting visions==0.7.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Using cached visions-0.7.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.16.0 in C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas-profiling) (2.5.3)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Using cached htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [27 lines of output]
  Traceback (most recent call last):
    File "C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\vaibh\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\vaibh\AppData\Local\Temp\pip-build-env-jk9ew2n0\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\vaibh\AppData\Local\Temp\pip-build-env-jk9ew2n0\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\vaibh\AppData\Local\Temp\pip-build-env-jk9ew2n0\overlay\Lib\site-packages\setuptools\build_meta.py", line 520, in run_setup
      super().run_setup(setup_script=setup_script)
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\vaibh\AppData\Local\Temp\pip-build-env-jk9ew2n0\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
      exec(code, locals())  # noqa: S102 # exec is intentional here
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 4, in <module>
    File "C:\Users\vaibh\AppData\Local\Temp\pip-install-06u5o9w7\htmlmin_76bf63558ea94a6881d1482869f39ddc\htmlmin\__init__.py", line 28, in <module>
      from .main import minify, Minifier
    File "C:\Users\vaibh\AppData\Local\Temp\pip-install-06u5o9w7\htmlmin_76bf63558ea94a6881d1482869f39ddc\htmlmin\main.py", line 28, in <module>
      import cgi
  ModuleNotFoundError: No module named 'cgi'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'htmlmin' when getting requirements to build wheel

In [7]:
%pip install -U ydata-profiling

Note: you may need to restart the kernel to use updated packages.

ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7,<3.11; 4.1.0 Requires-Python >=3.7,<3.12; 4.1.1 Requires-Python >=3.7,<3.12; 4.1.2 Requires-Python >=3.7,<3.12; 4.10.0 Requires-Python >=3.7,<3.13; 4.11.0 Requires-Python >=3.7,<3.13; 4.12.0 Requires-Python >=3.7,<3.13; 4.12.1 Requires-Python >=3.7,<3.13; 4.12.2 Requires-Python >=3.7,<3.13; 4.13.0 Requires-Python >=3.7,<3.13; 4.14.0 Requires-Python >=3.7,<3.13; 4.15.0 Requires-Python >=3.7,<3.13; 4.15.1 Requires-Python >=3.7,<3.13; 4.16.0 Requires-Python >=3.7,<3.13; 4.16.1 Requires-Python >=3.7,<3.13; 4.17.0 Requires-Python >=3.7,<3.14; 4.18.0 Requires-Python >=3.10,<3.14; 4.18.1 Requires-Python >=3.10,<3.14; 4.18.4 Requires-Python >=3.10,<3.14; 4.2.0 Requires-Python >=3.7,<3.12; 4.3.0 Requires-Python >=3.7,<3.12; 4.3.1 Requires-Python >=3.7,<3.12; 4.3.2 Requires-Python >=3.7,<3.12; 4.4.0 Requires-Python >=3.7,<3.12; 4.5.0 Requires-Python >=3.7,<3.12; 4.5.1 Requires-Python >=3.7,<3.12; 4.6.0 Requires-Python >=3.7,<3.12; 4.6.1 Requires-Python >=3.7,<3.12; 4.6.2 Requires-Python >=3.7,<3.12; 4.6.3 Requires-Python >=3.7,<3.12; 4.6.4 Requires-Python >=3.7,<3.12; 4.6.5 Requires-Python >=3.7,<3.12; 4.7.0 Requires-Python >=3.7,<3.13; 4.8.3 Requires-Python >=3.7,<3.13; 4.9.0 Requires-Python >=3.7,<3.13
ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling

In [8]:
import pandas as pd
from ydata_profiling import ProfileReport

ModuleNotFoundError: No module named 'ydata_profiling'

In [ ]:
# Old way (Do not use)
# import pandas_profiling

# New correct way
from ydata_profiling import ProfileReport
import pandas as pd

# Load your data and generate the report as normal
df = pd.read_csv("your_data.csv")
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("your_report.html")

In [ ]:
from ydata_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='output.html')

In [11]:
%pip install -U ydata-profiling

Note: you may need to restart the kernel to use updated packages.

ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7,<3.11; 4.1.0 Requires-Python >=3.7,<3.12; 4.1.1 Requires-Python >=3.7,<3.12; 4.1.2 Requires-Python >=3.7,<3.12; 4.10.0 Requires-Python >=3.7,<3.13; 4.11.0 Requires-Python >=3.7,<3.13; 4.12.0 Requires-Python >=3.7,<3.13; 4.12.1 Requires-Python >=3.7,<3.13; 4.12.2 Requires-Python >=3.7,<3.13; 4.13.0 Requires-Python >=3.7,<3.13; 4.14.0 Requires-Python >=3.7,<3.13; 4.15.0 Requires-Python >=3.7,<3.13; 4.15.1 Requires-Python >=3.7,<3.13; 4.16.0 Requires-Python >=3.7,<3.13; 4.16.1 Requires-Python >=3.7,<3.13; 4.17.0 Requires-Python >=3.7,<3.14; 4.18.0 Requires-Python >=3.10,<3.14; 4.18.1 Requires-Python >=3.10,<3.14; 4.18.4 Requires-Python >=3.10,<3.14; 4.2.0 Requires-Python >=3.7,<3.12; 4.3.0 Requires-Python >=3.7,<3.12; 4.3.1 Requires-Python >=3.7,<3.12; 4.3.2 Requires-Python >=3.7,<3.12; 4.4.0 Requires-Python >=3.7,<3.12; 4.5.0 Requires-Python >=3.7,<3.12; 4.5.1 Requires-Python >=3.7,<3.12; 4.6.0 Requires-Python >=3.7,<3.12; 4.6.1 Requires-Python >=3.7,<3.12; 4.6.2 Requires-Python >=3.7,<3.12; 4.6.3 Requires-Python >=3.7,<3.12; 4.6.4 Requires-Python >=3.7,<3.12; 4.6.5 Requires-Python >=3.7,<3.12; 4.7.0 Requires-Python >=3.7,<3.13; 4.8.3 Requires-Python >=3.7,<3.13; 4.9.0 Requires-Python >=3.7,<3.13
ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling

In [1]:
!python --version

Python 3.14.8