# Column Transaction

In [1]:
import numpy as np 
import pandas as pd

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [10]:
X_train

    age  gender  fever   cough       city
32   34  Female  101.0  Strong      Delhi
50   19    Male  101.0    Mild      Delhi
78   11    Male  100.0    Mild  Bangalore
3    31  Female   98.0    Mild    Kolkata
29   34  Female    NaN  Strong     Mumbai
..  ...     ...    ...     ...        ...
67   65    Male   99.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
61   81  Female   98.0  Strong     Mumbai
10   75  Female    NaN    Mild      Delhi
82   24    Male   98.0    Mild    Kolkata

[80 rows x 5 columns]

In [11]:
X_test

    age  gender  fever   cough       city
99   10  Female   98.0  Strong    Kolkata
6    14    Male  101.0  Strong  Bangalore
23   80  Female   98.0    Mild      Delhi
85   16  Female  103.0    Mild  Bangalore
19   42  Female    NaN  Strong  Bangalore
38   49  Female  101.0    Mild      Delhi
71   75  Female  104.0  Strong      Delhi
64   42    Male  104.0    Mild     Mumbai
41   82    Male    NaN    Mild    Kolkata
72   83  Female  101.0    Mild    Kolkata
16   69  Female  103.0    Mild    Kolkata
86   25    Male  104.0    Mild  Bangalore
74   34  Female  104.0  Strong      Delhi
30   15    Male  101.0    Mild      Delhi
44   20    Male  102.0  Strong      Delhi
57   49  Female   99.0  Strong  Bangalore
68   54  Female  104.0  Strong    Kolkata
84   69  Female   98.0  Strong     Mumbai
88    5  Female  100.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi

# 1.normaly

In [35]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever= si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [36]:
oe=OrdinalEncoder(categories= [['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])

X_test_cough= oe.fit_transform(X_test[['cough']])

In [37]:
X_train_cough.shape

(80, 1)

In [44]:
ohe=OneHotEncoder(drop='first',)
X_train_gender=ohe.fit_transform(X_train[['gender','city']]).toarray()

X_test_gender= ohe.fit_transform(X_test[['gender','city']]).toarray()

In [45]:
X_train_gender.shape

(80, 4)

In [46]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

In [47]:
X_train_age.shape

(80, 1)

In [48]:
X_train_transformed= np.concatenate((X_train_age,X_train_fever,X_train_gender,X_train_cough),axis=1)

X_test_transformed= np.concatenate((X_test_age,X_test_fever,X_test_gender,X_test_cough),axis=1)

In [49]:
X_train_transformed.shape

(80, 7)

# 2. By using Column Transform

In [50]:
from sklearn.compose import ColumnTransformer

In [61]:
transformer=ColumnTransformer(transformers=[('a1',SimpleImputer(),['fever']),
                                            ('a2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('a3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
                                           ],remainder='passthrough')

In [62]:
transformer.fit_transform(X_train).shape

(80, 7)

In [63]:
transformer.transform(X_test).shape

(20, 7)